Better Error Message for Bad Redis URLs
In the past a Redis URL missing the redis:// protocol would result in an
experience like this:

```
cleaning up...
Deploying [==>------] 33% [plugin: redis ->
fetchInitialRevisions]events.js:183
throw er; // Unhandled 'error' event
            ^

Error: Redis connection to 127.0.0.1:6379 failed - connect
ECONNREFUSED 127.0.0.1:6379
  at Object._errnoException (util.js:1022:11)
  at _exceptionWithHostPort (util.js:1044:20)
  at TCPConnectWrap.afterConnect [as oncomplete]
    (net.js:1182:14)
```

This experience doesn't provide a helpful error message. Going forward
the experience would be:

```
Your Redis URL appears to be missing the "redis://" protocol. Update your URL to: redis://host.amazonaws.com:6379/4
```

This would happen even before we attempt to connect to Redis.

Resolves #82